language: java
sudo : true
services:
- postgresql
env:
  global:
  - PGPORT=5432
before_install:
- chmod +x mvnw
before_script:
- psql -c 'create database db_annualAppraisal;' -U postgres
- psql -c "CREATE USER foo WITH PASSWORD '';" -U postgres
- psql -h localhost --username=postgres --list
test:
  adapter: postgresql
  database: db_annualAppraisal
  username: postgres
  encoding: utf8
script:
- cd Back-end
- mvn clean install
